### PR TITLE
Website: Add "awesome-taskfile" repo to "Community" page

### PR DESCRIPTION
**Pull request by hhstore**
- Collect some Taskfiles written by community developers

### CODE REVIEW

**Comment by ghostsquad** [comment]
I like the theory of this change, but I just browsed the repos mentioned, and the task files look quite basic.

I also don't know where the 5-star rating is coming from, or if that would set a precedence that some task files could get lower ratings, which could prevent people from showcasing their work.

**Comment by hhstore** [comment]
- https://github.com/better-sre/config/tree/main/taskfile
- https://github.com/better-sre/config/blob/main/docker-compose/local/Taskfile.yml
- I've written a lot of Taskfile scripts.
-You may not have looked carefully. In these directories. There are many scripts.

**Comment by hhstore** [comment]
## about include `Taskfile`:

- About reusing Taskfile in different projects. I gave 3 feasible solutions.
- I'm wondering if go-task can support option 2 or option 3.


image


> like this : 


```yml

includes:
  sre:
    taskfile:  "https://github.com/better-sre/config"
    type: git+local  # or git+global
    dir: ./.task/        # or ~/.task/
    sync: auto  # sync github: daily 

```

**Comment by ghostsquad** [comment]
@hhstore ya, I saw the Taskfiles, lots of them. I didn't see very many examples that I felt were actually better than alternative commands, or tasks that I were abstract enough to warrant reuse. I'm not saying they aren't useful to some...

My point about the stars was actually that they should be removed.

**Comment by hhstore** [comment]
> @hhstore ya, I saw the Taskfiles, lots of them. I didn't see very many examples that I felt were actually better than alternative commands, or tasks that were abstract enough to warrant reuse. I'm not saying they aren't useful to some...
> 
> My point about the stars was actually that they should be removed.


- How complicated can daily development, installation commands, project initialization and other scripts be? Most of these are just some dirty work.
- What do you think is worth sharing? You can share the better scripts you wrote.
- I don't know why the stars ⭐ bother you. Just ignore  them.

**Comment by ghostsquad** [comment]
Ya, that's fair. I suppose sharing anything at all is a start to help people explore the possibility space.

**Comment by ssbarnea** [comment]
How about a little bit different approach, advertise https://github.com/topics/taskfile url which is listing all repositories related to `taskfile` topic, sorted by github stars. This is like having a dynamic list of resources which does not need maintenance.

If example repos become more popular (stars), their listing would appear upper. This also works for advertising which other projects are using taskfiles. We should recommend our users to add the `taskfile` topic to their repositories. I already did that with two and likely more popular ones will follow.

I would also advertise using https://sourcegraph.com/search?q=context:global+file:Taskfile.yml&patternType=literal to perform searches on other repositories that use taskfiles. It proved to be useful for me to discover how others are using as some use cases are not yet documented. That site is like github advanced search on steroids, allowing to do much more than github version. That is also how I found other popular projects using taskfiles.

**Comment by ssbarnea** [comment]
@hhstore You should add the `taskfile` topic to your repository, so it would be listed on https://github.com/topics/taskfile page, a page I recently helped by making the topic more official (see logo and description).

**Comment by hhstore** [comment]
> @hhstore You should add the `taskfile` topic to your repository, so it would be listed on https://github.com/topics/taskfile page, a page I recently helped by making the topic more official (see logo and description).


- https://github.com/better-sre/awesome-taskfile
- I have added this tag(taskfile).
- The reason why this project was created is to `manually collect` more use cases and better `reuse the work of others`.
- Because many people `don't add tags`. Unfortunately, the program can't find them.
- Moreover, the existence of such a repo also `encourages more people to share` their achievements here.

**Comment by ssbarnea** [comment]
@hhstore People do no add tags because they do not know about them and because we never advertised them. Still, you change can also fix that and recommend everyone to add "taskfile" topic to their repository, as this being a nice way to show their appreciation for the tool and at the same time make it easier for potential contributors to find information about taskfile.

I already starred your repo. Be patience getting stars takes time but as much as you think.

Once the PR merges feel free to tweet about it and taskfile as this might encourage others to look at it.

**Comment by andreynering** [comment]
Hi @hhstore,

The idea may be good, but given the repo is a bit too basic currently, I'm going to close this PR.

If this PR (or other like this) become more complete and popular in the future, I may consider to link it in the website.

**Pull request closed without merging**
