### PR TITLE
Added fish completions

### PR DESCRIPTION
**Pull request by shilangyu**
Completes available tasks:

image

Completes available flags:

image

Completes available options for flags:

image

### CODE REVIEW

**Comment by andreynering** [comment]
Thanks @shilangyu!

**Comment by onedr0p** [comment]
@shilangyu how do you install this? I tried... 

```bash
wget https://raw.githubusercontent.com/go-task/task/master/completion/fish/task.fish -O ~/.config/fish/functions/task.fish

source ~/.config/fish/functions/task.fish
```

But it's not completing.

**Comment by onedr0p** [comment]
image

**Comment by onedr0p** [comment]
image

**Comment by onedr0p** [comment]
I suggest using `tr ': ', '\t'` instead of `sed 's/: /\t/'` to make this work in MacOS

**Comment by onedr0p** [comment]
PR opened

https://github.com/go-task/task/pull/371

**Pull request merged**
