### PR TITLE
feat: v2 deprecation and experiments

### PR DESCRIPTION
**Pull request by pd93**
- Docs
  - Experiments
    - A section on the version 2 schema deprecation.
    - A template for future experiments/deprecations.
  - Experiments / Workflow
    - A subsection describing the workflow/procedure for adding experiments
  - Contribution Guide
    - A small section on experiments linking to the workflow
  - Taskfile versions
    - Added deprecation warnings
    - Reordered the file so that the newest schemas are at the top.
- Added an entry to the changelog to improve visibility of the v2 schema deprecation
- Updated issue templates
  - Use HTML comments so that people don't accidentally submit issues with the `>` quoted text
  - Added `Experiments enabled:` to the bug reports
- Added workflows that comment on an issue when experiment labels are added. Copy for each state is pasted below:

### Proposed

This issue has been marked as an experiment proposal! :test_tube: It will now enter a period of consultation during which we encourage the community to provide feedback on the proposed design. Please see the [experiment workflow documentation](https://taskfile.dev/experiments/workflow) for more information on how we release experiments.

### Draft

This experiment has been marked as a draft! :sparkles: This means that an initial implementation has been added to the latest release of Task! You can find information about this experiment and how to enable it in our [experiments documentation](https://taskfile.dev/experiments). Please see the [experiment workflow documentation](https://taskfile.dev/experiments/workflow) for more information on how we release experiments.

### Candidate

This experiment has been marked as a candidate! :fire: This means that the  implementation is nearing completion and we are entering a period for final comments and feedback! You can find information about this experiment and how to enable it in our [experiments documentation](https://taskfile.dev/experiments). Please see the [experiment workflow documentation](https://taskfile.dev/experiments/workflow) for more information on how we release experiments.

### Stable

This experiment has been marked as stable! :metal: This means that the  implementation is now final and ready to be released. No more changes will be made and the experiment is safe to use in production! You can find information about this experiment and how to enable it in our [experiments documentation](https://taskfile.dev/experiments). Please see the [experiment workflow documentation](https://taskfile.dev/experiments/workflow) for more information on how we release experiments.

### Released

This experiment has been released! :rocket: This means that this is no longer an experiment and is available in the latest major version of Task. Please see the [experiment workflow documentation](https://taskfile.dev/experiments/workflow) for more information on how we release experiments.

### Abandoned

This experiment has been abandoned. :disappointed: This means that this feature will not be added to Task and any experimental functionality will be removed. Please see the [experiment workflow documentation](https://taskfile.dev/experiments/workflow) for more information on how we release experiments.

### Superseded

This experiment has been superseded. :seedling: This means that another experiment has replaced this one. Please see the [experiment workflow documentation](https://taskfile.dev/experiments/workflow) for more information on how we release experiments.

### CODE REVIEW

**Comment by pd93** [comment]
FYI - I've split the code changes out into #1199 as there may be some discussion there. This PR just contains docs changes now.

**Comment by andreynering** [comment]
Thanks!

I have mixed feeling about using images for labels. It adds visibility but hurts SEO and accessibility. I think we can merge now and improve later if it shows needed.

**Comment by pd93** [comment]
> I have mixed feeling about using images for labels. It adds visibility but hurts SEO and accessibility. I think we can merge now and improve later if it shows needed.

Yeah, that's fair enough. I hadn't considered this when authoring. I was just trying to break up the wall of text and make the labels more visible. No objection to changing them to backticks instead.

I didn't actually know that GitHub has [this functionality](https://github.blog/changelog/2022-02-03-reference-labels-in-markdown/), but sadly this won't work in Docusaurus. Maybe there is an MDX plugin for rendering github labels?

**Comment by andreynering** [comment]
I think it's unlikely that there will be a plugin for that.

**Comment by pd93** [comment]
For future reference:

- https://github.com/remarkjs/remark-gfm
- https://github.com/remarkjs/remark-github

I doubt that these have the label functionality, but they might be super useful for other things (like not having to translate issue references into FQDNs etc. I gave it a quick go, but looks like there are some compatibility issues with ES modules in Docusaurus. Might be nice to revisit this sometime.

**Pull request merged**
