### PR TITLE
Move path expanding logic to shell.Expand

### PR DESCRIPTION
**Pull request by andreynering**
@mvdan Continuing discussion from https://github.com/go-task/task/commit/102f8ab74e77010a95a8c12957828d8be38327b1

Sorry but `shell.Expand` is not yet working right. I'm still getting:

```
could not stat: stat /Users/andrey/repos/GOPATH/src/github.com/go-task/task/testdata/expand/~: no such file or directory
```

### CODE REVIEW

**Comment by andreynering** [comment]
Hmm... since this passed on Travis, I now think it may be an issue with macOS

**Comment by mvdan** [comment]
That's weird - I run all the tests, including the fix for this case, on Mac via Travis.

Do you have a minimal case to reproduce this, ideally that's runnable on Travis? I don't have any Mac machine to run tests on myself.

**Comment by andreynering** [comment]
I didn't know Travis supported Mac

I'll try to create a snippet to reproduce the issue once a have a bit of time

**Comment by andreynering** [comment]
@mvdan Nevermind, I should have missed running `go install` before trying or anything

This seems to be working fine 🙂

**Pull request merged**
