### PR TITLE
Add support for exclude rules for sources

### PR DESCRIPTION
**Pull request by lunny**
When I use task to package a directory which includes `node_modules`, I found it will spend about 7 seconds even if I have set `sources`. And I found that's because `task` needs exclude rules, so I write this PR and now I can set as below:

```yaml
sources:
      - "!web/.*"
      - "!web/node_modules/**"
      - "!web/tests/**"
      - "!web/dist/**"
      - "!web/mock/**"
      - "!web/LICENSE"
      - "!web/*.md"
      - "!web/**/*.md"
      - web/**
method: checksum
```

After the change, it will spend only `0.29s`. Yeah!

### CODE REVIEW

**Comment by lunny** [comment]
@andreynering 
1. I will change the base branch to v3
2. I will not update vendor
3. I found https://github.com/mattn/go-zglob/blob/a8912a37f9e79ee444e77452cba926b3e5b09a65/zglob.go#L27 , that `zenv` is unexported, so that it could not be saved. If we have multiple rules, it's low performance. So I suggest to drop zglob and keep the new one. But for this PR, I won't to touch other place which depends on zglob. So that it's easier to review. On further PRs, zglob could be replaced totally.

**Comment by lunny** [comment]
@andreynering done.

**Comment by andreynering** [comment]
Closed by mistake, sorry

**Comment by marco-m** [comment]
Hello, what is the status of this PR? From #225 I understand it is complicated, but I have hope :-)

**Comment by butuzov** [comment]
@andreynering is there any updates on this issue? Having something to exclude is quite a nice feature to have.

**Comment by tamasfe** [comment]
@andreynering is there anything I could do to help with driving this forward? It would be a crucial feature for me as currently code generation patterns (e.g. `generating **/*.gen.go` based on `**/*.go`) do not seem possible without workarounds.

**Comment by kevpie** [comment]
> @andreynering is there anything I could do to help with driving this forward? It would be a crucial feature for me as currently code generation patterns (e.g. generating `**/*.gen.go` based on `**/*.go`) do not seem possible without workarounds.

How promising does helping getting https://github.com/mattn/go-zglob/pull/30 landed go towards solving this?

**Pull request closed without merging**
