### PR TITLE
Try out Windows builds in Travis

### LINKED ISSUE #171: Setup CI to run on Windows
Pretty important to catch bugs like those found on https://github.com/go-task/task/pull/170

### PR DESCRIPTION
**Pull request by emirb**
Closes #171

### CODE REVIEW

**Comment by andreynering** [comment]
@emirb Thanks!

I'll want until we have all fixes for Windows before merging it, though.

**Comment by andreynering** [comment]
Hi @emirb,

Can you try merging master into this branch?

**Comment by emirb** [comment]
Rebased @andreynering.

**Comment by andreynering** [comment]
Hmm... seems that Travis run tests on a Bash-like environment. Otherwise some tests would fail (due lack of `touch` and other built-ins).

Good to go, but we can still improve Windows support on non-Bash environments with time.

@emirb Thanks again! Merging this.

**Pull request merged**
