### PR TITLE
add help task

### PR DESCRIPTION
**Pull request by zbindenren**
For large projects sometimes it is nice to have a help task, that lists the most important tasks.

### CODE REVIEW

**Comment by sascha-andres** [comment]
I like the idea. Maybe we could amend this to print out dependencies?

**Comment by zbindenren** [comment]
I would do the depgraph with an option.

task -d target shows depgraph for target, task -d shows depgraph for all targets?

**Comment by andreynering** [comment]
Thank you very much.

Merged manually as https://github.com/go-task/task/commit/e4c1cc3e7765d25c4f7cedd0544405872ba37241

**Comment by zbindenren** [comment]
Thx

**Pull request closed without merging**
