### PR TITLE
powershell completion: disable file path autocomplete / add flags

### PR DESCRIPTION
**Pull request by trim21**
> Thanks for your pull request, we really appreciate contributions!
>
> Please understand that it may take some time to be reviewed.
>
> Also, make sure to follow the [Contribution Guide](https://taskfile.dev/contributing/).

Didn't know there is a command `task --list-all --json/--silent` for all available tasks when I submit last PR.

Previous, if your pwd have a dir or file named `gen` or `gen...`, and you have a task named `gen`,
when you type `task gen<tab>`, powershell will fallback to filepath complete, and your input will become `task .\gen`

after this pr, `task gen<tab>` are still `task gen`

File path auto completion still works with `.\<tab>` or `./<tab>`

### CODE REVIEW

**Comment by trim21** [comment]
I try to add short opt but looks like old powershell (5.1, win10 default version) doesn't work will with that, So I'll just add long flags.

**Comment by trim21** [comment]
adding description feature, convert to draft

**Comment by trim21** [comment]
description can also be padded to look better, but maybe leave it to someone who are interested.

**Comment by trim21** [comment]
description feature make it much slower to finish completion ( I guess it's caused by parse json), so I removed it.

**Comment by andreynering** [comment]
Thanks!

**Pull request merged**
