### PR TITLE
remove Chinese in sidebar

### PR DESCRIPTION
**Pull request by trim21**
> Thanks for your pull request, we really appreciate contributions!
>
> Please understand that it may take some time to be reviewed.
>
> Also, make sure to follow the [Contribution Guide](https://taskfile.dev/contributing/).

### CODE REVIEW

**Comment by pd93** [comment]
The Chinese translation linked in the sidebar was originally submitted by @DeronW. Since a lot of progress has now been made via the CrowdIn integration (including a Chinese translation), I wonder if it makes sense to move towards that implementation instead rather than maintaining two links in our official documentation?

@DeronW I'm very conscious that you probably spent a lot of time working on your translation and we're very grateful for this. How would you feel about helping to maintain the official translations via CrowdIn instead so that we can keep everything in a central place?

**Comment by misitebao** [comment]
@pd93 @andreynering 
/cc @DeronW

I think after migrating the docs to Crowdin it seems like the link could be removed. [@DeronW seems to agree](https://github.com/go-task/task/issues/1057#issuecomment-1478954431).

**Comment by pd93** [comment]
> I think after migrating the docs to Crowdin it seems like the link could be removed.

@misitebao Thanks for pointing that out, I hadn't seen that comment.

@trim21 Would you consider updating this PR to remove the sidebar link?

@DeronW if you ever want to contribute again, you're very welcome to [request access to CrowdIn](https://crowdin.com/project/taskfile) and we'll grant you access

**Comment by misitebao** [comment]
@trim21 
The following files also need to be updated to remove the corresponding content:

1. `/docs/i18n/en/docusaurus-plugin-content-docs/current.json`
2. `/docs/i18n/en/docusaurus-theme-classic/footer.json`

**Review by misitebao — COMMENTED** [review]
@trim21 
The following files also need to be updated to remove the corresponding content:

1. `/docs/i18n/en/docusaurus-plugin-content-docs/current.json`
2. `/docs/i18n/en/docusaurus-theme-classic/footer.json`

**Comment by andreynering** [comment]
Thanks @trim21! I just manually merged this at 0aa6c5eae8b20fb40e9912b1c2c62a8c504f1798.

**Pull request closed without merging**
