### PR TITLE
Add golangci-lint

### PR DESCRIPTION
**Pull request by andreynering**
Adding [staticcheck](https://staticcheck.io/) to prevent simple bugs on the code. Once merged, I'll make this CI step required for merging (done that for the tests themselves already).

### CODE REVIEW

**Review by ghostsquad — COMMENTED** [review]
Implement https://golangci-lint.run/ instead. It aggregates a lot of checks at the same time.

**Comment by andreynering** [comment]
@ghostsquad I had the impression that golangci-lint would be that kind of extremely-aggressive linter, which I dislike. Tried it and end up that the default rules are actually very reasonable 👍

**Review by ghostsquad — COMMENTED** [review]
Here's a `.golangci.yml` file to enable as many linters as possible (pulled from another project):

```yaml
linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/golangci/golangci-lint
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport  # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true  # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false  # report any unused nolint directives
    require-explanation: false  # don't require an explanation for nolint directives
    require-specific: false  # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
```

**Comment by andreynering** [comment]
@ghostsquad That seems too much for me. I was trying to avoid exactly that. [The default set](https://golangci-lint.run/usage/linters/#enabled-by-default) seems reasonable enough for me. Let's start with that.

**Comment by ghostsquad** [comment]
> @ghostsquad I had the impression that golangci-lint would be that kind of extremely-aggressive linter, which I dislike. Tried it and end up that the default rules are actually very reasonable 👍

Ya, I no harm in just enabling as much as possible, and seeing what low-hanging-fruit can be resolved quickly. Then adding inline lint-ignore comments in areas in code that improvement so you don't need to boil the ocean all at once.

**Comment by ghostsquad** [comment]
> @ghostsquad That seems too much for me. I was trying to avoid exactly that. [The default set](https://golangci-lint.run/usage/linters/#enabled-by-default) seems reasonable enough for me. Let's start with that.

That's fair. Comment is still here for us to come back to later. 🙂

**Review by ghostsquad — APPROVED** [review]

**Pull request merged**
