### PR TITLE
chore(deps): switch to mainted fork of `git-urls`

### PR DESCRIPTION
**Pull request by AlekSi**
Switch from https://github.com/whilp/git-urls to https://github.com/chainguard-dev/git-urls. See https://github.com/whilp/git-urls/issues/24 and https://github.com/whilp/git-urls/issues/28. Many scanning tools complain about that.

### CODE REVIEW

**Review by andreynering — APPROVED** [review]
Thanks!

**Comment by AlekSi** [comment]
What should be done to merge and release this?

**Comment by vmaerten** [comment]
Thanks!

**Review by vmaerten — APPROVED** [review]

**Comment by AlekSi** [comment]
Could you please make a patch release?

**Comment by AlekSi** [comment]
@vmaerten @andreynering Sorry to bother you, but could you please tag a new release?

**Comment by AlekSi** [comment]
@andreynering Thank you very much!

**Pull request merged**
