### PR TITLE
allow running dependencies serially

### PR DESCRIPTION
**Pull request by dtomasi**
In some cases we have to run dependency tasks serially. I added a option to the taskfile to allow this.

### CODE REVIEW

**Comment by andreynering** [comment]
Hi again @dtomasi,

Before accepting this feature request, I'd like to understand if there's real need for it.

Nowadays, it should already possible to run things serially: you just need to declare it directly in `cmds` instead of in `deps`:

```yaml
version: '2'

tasks:
  default:
    cmds:
      - task: foo
      - task: bar
      - echo "..."
```

Instead of:

```yaml
version: '2'

tasks:
  default:
    deps: [foo, bar]
    cmds:
      - echo "..."
```

Is there any reason why the above isn't enough to satisfy your use case?

**Comment by dtomasi** [comment]
Hi @andreynering 

As described in #226 

```yaml
tasks:
  default:
    cmds:
      - task: foo
      - task: bar
      - echo "..."
```

will not work for me, as I want to skip the dependencies. Skipping the first 3 `cmds` in the list is not possible ;-)

**Comment by smyrman** [comment]
I think I hold with @andreynering's suggestion in #226 that you should rely on two tasks for what you want. Then you don't need neither of these two features:

```yaml
version: "2"

tasks:
  build:
    cmds:
    - task: foo
    - task: bar
    - task: build-no-deps
  build-no-deps:
    cmds:
    - echo "..."
```

The benefit for relying on the Taskfile over adding new flags, is that you state what you want in a _declarative_ way, rather than adding flags that _alter_ how things are run.

**Comment by dtomasi** [comment]
> Prevent unnecessary work 

Coming from your documentation ;-) 
I´m not really happy with this suggested workaround. However, will keep this feature in my fork then, as I really want to use it as described. 

Cheers

**Comment by andreynering** [comment]
Hi @dtomasi,

I'm going to reject both proposals for now as IMO this use case is already possible today with changes in your Taskfile (my making tasks less coupled / dependent on each other).

I'm sorry, but thanks anyway for opening these pull requests!

I can revisit this decision in the future if more people show interest or need in these features.

**Pull request closed without merging**
