### PR TITLE
#338: Handle an empty task in a file

### PR DESCRIPTION
**Pull request by bharathshetty4**

### CODE REVIEW

**Comment by andreynering** [comment]
Hi @bharathshetty4, thanks for opening this pull request!

I think I have a slightly better idea: I think we can just assign an empty task if the pointer is `nil`:

```go
if t == nil {
        t = &taskfile.Task{}
}
```

This should be enough to prevent panics without having to keep checking for `nil` on many places...

**Comment by bharathshetty4** [comment]
> Hi @bharathshetty4, thanks for opening this pull request!
> 
> I think I have a slightly better idea: I think we can just assign an empty task if the pointer is `nil`:
> 
> ```go
> if t == nil {
>         t = &taskfile.Task{}
> }
> ```
> 
> This should be enough to prevent panics without having to keep checking for `nil` on many places...

Hi @andreynering checked by ``` t = &taskfile.Task{}``` this doesn't solve the nil problem for an empty task, as the task uses task.Var while running that task. We had use these nil checks to get rid.

**Comment by bharathshetty4** [comment]
> Hi @bharathshetty4, thanks for opening this pull request!
> 
> I think I have a slightly better idea: I think we can just assign an empty task if the pointer is `nil`:
> 
> ```go
> if t == nil {
>         t = &taskfile.Task{}
> }
> ```
> 
> This should be enough to prevent panics without having to keep checking for `nil` on many places...

this is done.

**Comment by andreynering** [comment]
Hi @bharathshetty4,

I manually merged that here: d78f78bb5cdd94fec59244121bdc1130547beb2b

Thanks for contributing!

**Pull request closed without merging**
