### PR TITLE
Add Fedora Linux to installation

### PR DESCRIPTION
**Pull request by mefuller**
Added Task to Fedora official repositories

I'm a Fedora  Linux packager and I have just added Task to the Fedora repositories.
I would appreciate you adding Fedora to the installation documentation.

Thanks,
-fuller

### CODE REVIEW

**Comment by ghostsquad** [comment]
Documentation without automation will set a precedence to keep this package repository up to date. Can you describe the plan you have that can allow this repository to be updated when a new version of task is released?

**Comment by andreynering** [comment]
Hi @mefuller. That's awesome, thanks!

@ghostsquad It's alright. We have other releases that are community owned, and we can always remove if any of them stop being maintained. Also, @mefuller seems to be an actual Fedora contributor.

**Comment by ghostsquad** [comment]
> Hi @mefuller. That's awesome, thanks!
> 
> @ghostsquad It's alright. We have other releases that are community owned, and we can always remove if any of them stop being maintained. Also, @mefuller seems to be an actual Fedora contributor.

Cool!

**Comment by mefuller** [comment]
Good morning.
Just to clarify @ghostsquad concerns, I am a contributor (packager) with Fedora.
The task package is primarily my responsibility, but is also in our golang special interest group where we have other contributors who can step in should I fail to maintain it.
We utilize release monitoring to automatically file bugs against the package when out of date and notify the owner (me) as well as the go group.

**Comment by ghostsquad** [comment]
Thanks for helping me understand the process @mefuller

**Pull request merged**
