### PR TITLE
Add interactive input system

### PR DESCRIPTION
**Pull request by JulienBreux**
## Link

🔗 https://github.com/go-task/task/issues/235

## Todo

- [x] Feature MVP (required, default, validator regexp)
- [x] Get feedback
- [ ] Add verbose logs
- [ ] Tests
- [ ] Commits clean/rebase

## Description

The need is to be able to request inputs.

### File: `Taskfile.yaml`

```yaml
version: "2"

task:
  aTaskWithInput:
    inputs:
      foo:
        required: true
      bar:
        default: "🍻"
        desc: "Do you love beer?"
      baz:
        validator: "([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))"
```

### How to use?

```shell
$ task aTaskWithInput
$ foo (required: yes)
$ <input>
$ Do you love beer? (default: 🍻)
$ <input>
$ baz (must validate: "([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))")
$ <input>
```

### CODE REVIEW

**Comment by andreynering** [comment]
Hi @JulienBreux,

Let's discuss this a bit before continuing...

What's your use case for it? Why do you prefer it to passing [variables](https://taskfile.dev/#/usage?id=variables) via CLI or environment variables?

(Also, if we're going to have this feature, I'd prefer to target it to the `v3` branch instead of `master`).

**Comment by JulienBreux** [comment]
Hi @andreynering,

> What's your use case for it? Why do you prefer it to passing [variables](https://taskfile.dev/#/usage?id=variables) via CLI or environment variables?

My use case is very simple ; add more user interaction with go-task.

Variables are very cool but a bit unsecure (history in your shell) and more static (only on running command).

The idea is to have the capability of pompt the user and re-use command with go-task.

## Possible use case

Request something to user (password, token, etc).

**Comment by smyrman** [comment]
https://github.com/AlecAivazis/survey has some nice options for input; a go-task interactive mode could potentially use that for setting task and/or global variables. Require a yaml validaition model that maps to the different input options one would want to support.

**Comment by andreynering** [comment]
Hi @JulienBreux,

Indeed, I think passwords are a great use case for it!

As an additional feedback:

1) For a matter of simplicity, I think I'd get rid of the "validator" stuff. If the most common use case will be for passwords and tokens, this wouldn't be much useful (since passwords doesn't have a pettern)
2) Do we really need the `--interactive` flag? Shouldn't we always ask for input if the task requires it?

**Comment by andreynering** [comment]
> https://github.com/AlecAivazis/survey has some nice options for input; a go-task interactive mode could potentially use that for setting task and/or global variables. Require a yaml validaition model that maps to the different input options one would want to support.

That seems an interesting project. I like how it allows to ask to select a value from a list of possible values (as an alternative to free text).

**Comment by JulienBreux** [comment]
Nice, I work on it this night (UTC+1).

Thanks for your feedbacks 🤗

**Comment by marco-m** [comment]
@andreynering 

> Indeed, I think passwords are a great use case for it!

I am a minimalist and I like that Task tries to stay minimal. In this optics, I would like to suggest an alternative to the proposal in this PR that, I think, doesn't require to change Task at all.

It is possible to use the OS secure storage and make the secrets available to Task as environment variables via a wrapper. I use https://github.com/sorah/envchain with Task and it works flawlessly.

For example:

```
envchain FOO task ...
```

will run `task ...`, with all the environment variables for the `FOO` "namespace" extracted from the OS secure storage. On Mac it is the Keychain, on Linux it is Gnome Keyring.

Would this be a viable alternative ?

**Comment by andreynering** [comment]
@marco-m Indeed, accepting or rejecting proposals is hard.

But while I definitely care about simplicity and maintainability, I also see how this could be useful. This was also asked before more than once (see #92), so I think this is more than worth discussing. I still think the design and code should be as simple as possible.

Another important consideration is that envchain doesn't seem to support Windows, and it's a core Task selling point that it tries to work the best it can on every supported OS.

I'd say this isn't a target for v3, though. Perhaps v3.1. v3 has lot of target features already, and I think I'll even move some to v3.x in order to be able to release them sooner.

**Comment by marco-m** [comment]
@andreynering I understand, and I appreciate you taking the time to give your rationale.
I think it is possible to make envchain work in a Windows environment, but I agree that somebody would have to do the work.

**Comment by JulienBreux** [comment]
After long time, I think that the more efficient experience maybe a "command provider".
For example:

**Short**
```
tasks:
  myTask:
    cmds:
      - cmd: echo "Hello"
      - input: yyy
      - cmd: echo "Hi {{ .yyy }}!"
```

**Long**
```
tasks:
  myTask:
    cmds:
      - cmd: echo "Hello"
      - input:
         name: yyy
         default: xxx
         desc: "Do you love beer?"
         validator: "([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))"
      - cmd: echo "Hi {{ .yyy }}!"
```

**Comment by andreynering** [comment]
> After long time, I think that the more efficient experience maybe a "command provider".

Sorry for the long wait, I've been relatively busy recently.

It's not easy to address proposal sometimes, but I decided to close this for now, since other stuff is higher in the priority list. Also, seems it's still not totally clear what path we should take here. I may reconsider adding this in the future.

@JulienBreux I hope you undertand.

**Comment by Jarmos-san** [comment]
I stumbled across [#92](https://github.com/go-task/task/issues/92) through a Google Search, so I was wondering whether this feature implementation is still in the pipeline?

**Comment by JulienBreux** [comment]
Nope, this proposal was closed by @andreynering :)

**Comment by andreynering** [comment]
Hey guys, I just opened some issues about adding more interactivity to Task.

- https://github.com/go-task/task/issues/2077
- https://github.com/go-task/task/issues/2078
- https://github.com/go-task/task/issues/2079

**Comment by plutonium-239** [comment]
`bubbletea` is amazing!

**Pull request closed without merging**
